### ISSUE TITLE
[PE-D][Tester D] adding Name is not case-sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-1/tp#103]
I can still add johnny even though Johnny is already in the list. Unsure if this is intended or not but I feel that they would still both be classified as the same person.

![image.png](https://raw.githubusercontent.com/richiehx/ped/main/files/7f5dd50e-d2e8-4ee6-8796-a87e7afe7c0d.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: richiehx/ped#8

**Comment by SungMatt** [comment]
What do y'all think? I don't think this is that big of an issue though, there are people with the name deWitt, and there are people called "Dewitt", and they are separate.

**Comment by kenvynKwek** [comment]
> What do y'all think? I don't think this is that big of an issue though, there are people with the name deWitt, and there are people called "Dewitt", and they are separate.

Agreed, should be separate. Additionally:
- shouldn't be an scenario where the user adds a same person twice
- even if same first name, different last names will iron out this issue e.g. 'Johnny Sins' and 'Johnny Neutron'
