### ISSUE TITLE
[PE-D][Tester C] Filter by salary doesn't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-1/tp#109]
![image.png](https://raw.githubusercontent.com/lshaoqin/ped/main/files/9dc94e2d-7c89-44f7-82ad-3f256137bdc7.png)

Reproduction: Attempt to execute command `filter s/4000`. 

Result: Nothing happens.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: lshaoqin/ped#10

**Comment by XihuaZ** [comment]
Not a bug.  Salary within `s/` is used to detect `employee` with `salary` less than or equal to 4000 as per User Guide. Most of the sample `employee` have salary less than or equal to 4000.
