### ISSUE TITLE
[PE-D][Tester D] No department command details in the feature section

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-T16-1/tp#121]
No department command details in the feature section but can be found in the command summary. The bracket is also mismatching.

![image.png](https://raw.githubusercontent.com/richiehx/ped/main/files/0ffff4a9-4a29-41ad-9511-d4d0e707ae31.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: richiehx/ped#14

**Comment by SungMatt** [comment]
Duplicate of #93
