### ISSUE TITLE
Update project website

### ISSUE THREAD

**Issue by kenvynKwek** [AY2324S1-CS2103-T16-1/tp#28]
- [ ] Update project website user guide to reflect tables as shown in /docs/UserGuide.md
- /docs/UserGuide.md `add` and `list` sections' tables show correctly
- but [project website user guide](https://ay2324s1-cs2103-t16-1.github.io/tp/UserGuide.html) `add` and `list` sections' tables has wrong formatting

- [ ] Update project website homepage to show our **new** README.md
- currently displaying AddressBook Level-3's details

**Comment by SungMatt** [comment]
Remember to tag this with the appropriate milestone!
