### ISSUE TITLE
Add new 'attach task to employee' feature

### ISSUE THREAD

**Issue by kenvynKwek** [AY2324S1-CS2103-T16-1/tp#45]
attach tasks to be done to employees

similar to r/REMARK of the tutorial-adding-command tP task in [week 6](https://nus-cs2103-ay2324s1.github.io/tp/tutorials/AddRemark.html) (add bare minimum function first, can enhance later)

possible command format (subject to change): `task INDEX [task]`

eg. `task 1 pay raise`

Example enhancements that can be done in later versions/issues:
- be an optional param in `add` command
- able to attach multiple tasks (like attaching multiple departments)
- add reminders to task -> into notification feature later

**Comment by SungMatt** [comment]
Can reference the[ C-Tagging](
https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/projectDuke/index.html#c-tagging) task in the iP -- i've implemented it [here](https://github.com/SungMatt/ip/releases/tag/C-Tagging)!
