### ISSUE TITLE
Update the Developer Guide

### ISSUE THREAD

**Issue by SungMatt** [AY2324S1-CS2103-T16-1/tp#5]
[Update the Developer Guide](https://nus-cs2103-ay2324s1.github.io/website/schedule/week7/project.html#5-update-the-dg-user-stories-glossary-nfrs-use-cases)

Target user profile, value proposition, and user stories: Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.
Use cases: Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)
Non-functional requirements: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
Glossary: Define terms that are worth recording.

**Comment by SungMatt** [comment]
@XihuaZ Let's work on this together! Someone can do the user stories, and someone can do the use cases and NFRs. Let me know which part you prefer!

**Comment by XihuaZ** [comment]
I will complete the use cases and NFRs.

**Comment by XihuaZ** [comment]
Modify product scope needed
