### ISSUE TITLE
[PE-D][Tester C] Improper window sizing for certain help commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-1/tp#89]
![image.png](https://raw.githubusercontent.com/lshaoqin/ped/main/files/9dad5a92-e87d-4b58-9e16-5b2d73536271.png)

Reproduction:
1. Type in `help edit` or `help find`

Result:
An un-resizable window that does not display all of the available information

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lshaoqin/ped#5

**Comment by SungMatt** [comment]
Issue only occurs if the user does not close the help pane, but instead clicks off of it.

**Comment by SungMatt** [comment]
Steps to reproduce:
1. Type in `help`
1a. Help window should pop up
2. Click away from the help window (do not close it)
3. Return to ManageHR and type `help add`
4. Notice that the GUI clips part of the usage message away.
