### ISSUE TITLE
[PE-D][Tester D] Adding Person does not support adding of names with '/' eg. 's/o'

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-T16-1/tp#92]
The add command does not work for the command "add n/Johnny s/o elon p/91242712 e/johnnysins@gmail.com a/Johnny street, block 69, #05-05 s/5300 l/14 r/subordinate d/ R&D m/ Alex Yeoh"

This is a functionality bug as the name of the person is Johnny s/o elon but can not be added.

![image.png](https://raw.githubusercontent.com/richiehx/ped/main/files/a31098f9-3027-444c-bd0b-a35227642bdc.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: richiehx/ped#4

**Comment by kenvynKwek** [comment]
- User Guide specifies n/NAME parameter to only accept __alphabets__
- out of scope
