### ISSUE TITLE
[PE-D][Tester D] No mention of existing departments in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-T16-1/tp#95]
There is no mention of the existing departments in the User Guide. The application gives an error when I try to enter a random department.

![image.png](https://raw.githubusercontent.com/richiehx/ped/main/files/063b148a-e504-4642-88cf-0a53d60a959d.png)

![image.png](https://raw.githubusercontent.com/richiehx/ped/main/files/12fa7222-72ce-4bf1-b86b-b7c12539f6cb.png)

![image.png](https://raw.githubusercontent.com/richiehx/ped/main/files/09c866db-e7fe-4f2d-b511-4e20889e66af.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: richiehx/ped#5

**Comment by SungMatt** [comment]
.. I don't think this is an issue. For a quick start, its understood that some defaults will be provided, but it shouldn't be assumed that a random department of their choosing is auto-created for them.

**Comment by kenvynKwek** [comment]
> .. I don't think this is an issue. For a quick start, its understood that some defaults will be provided, but it shouldn't be assumed that a random department of their choosing is auto-created for them.

true, but i think we still have the issue of 'not having default set departments/data when starting ManageHR without saved data' that needs to be fix

maybe we can include this issue under the same umbrella as #83 and close this when #83 has been fixed
