### ISSUE TITLE
[PE-D][Tester C] Some fields are not displayed if information provided is too long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-1/tp#97]
![image.png](https://raw.githubusercontent.com/lshaoqin/ped/main/files/4fa75e19-30ff-4b3d-b512-e984fc1124d7.png)

![image.png](https://raw.githubusercontent.com/lshaoqin/ped/main/files/ae762410-9f88-4a71-8a14-623de5042451.png)

Reproduction: Create a person with a very long email or salary/leave

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: lshaoqin/ped#6

**Comment by SungMatt** [comment]
Alternative is to limit the length of an e-mail and the length of leave

**Comment by kenvynKwek** [comment]
- unrealistic issue
- valid emails already have reasonably sized length
- unlikely to have a salary above 6 figures
